### ISSUE TITLE
multiple concurrent Google logins not handled properly

### ISSUE THREAD

**Issue by lolwhat** [julianlam/nodebb-plugin-sso-google#18]
I have three different Google logins that I typically have open in my browser at the same time. I'm also a user on The Daily WTF forums, and that user is tied to one of those logins. Unfortunately, when logging into TDWTF forums, NodeBB doesn't let me choose which Google login to use, which usually means that it chooses the wrong one. Please provide a way for the user to select the correct Google login if he has more than one active. Thanks!

**Comment by lolwhat** [comment]
Paging @julianlam. @julianlam to the white courtesy phone, please. :smile:

**Comment by julianlam** [comment]
Hello! I use two logins myself... to my knowledge, when you have more than one active session open, it should let you choose which profile to use.

That's sort of out of NodeBB's control, really, since all we do is kickstart the login process and hand it over to Google. If they decide to choose the wrong one, I don't think we can even tell :frowning:

**Comment by lolwhat** [comment]
@julianlam, since you're the developer of NodeBB, please consider researching this issue further. It's difficult to believe that I'm the only one having this problem; besides, Google will more likely listen to you about it, since it's your product that interfaces with the Google SSO. Thank you.

**Comment by julianlam** [comment]
v1.3.0 requires upcoming NodeBB v1.0.4 (latest `master`)

**Comment by lolwhat** [comment]
Thanks, @julianlam! I sincerely appreciate it.
